"""empty message

Revision ID: 7013c50cc624
Revises: f827f4dafe57
Create Date: 2022-07-06 05:08:42.366305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7013c50cc624'
down_revision = 'f827f4dafe57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_urls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('short_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='short_urls_pkey'),
    sa.UniqueConstraint('short_id', name='short_urls_short_id_key')
    )
    # ### end Alembic commands ###
